// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNfmMtf-Bpcq1C5dTACL3dkgMdGSQXffk',
    appId: '1:898169829916:web:1af522fa9243a39c62fdd9',
    messagingSenderId: '898169829916',
    projectId: 'store-b683a',
    authDomain: 'store-b683a.firebaseapp.com',
    storageBucket: 'store-b683a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ7kvtR4nNOrrUkT9BmFT-Y8_ku4Q99ww',
    appId: '1:898169829916:android:d542083681f41ac962fdd9',
    messagingSenderId: '898169829916',
    projectId: 'store-b683a',
    storageBucket: 'store-b683a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzwyfcWSuLsXx-dnOzXgDoLh0h0I8tbRo',
    appId: '1:898169829916:ios:ca9394db78be1ac362fdd9',
    messagingSenderId: '898169829916',
    projectId: 'store-b683a',
    storageBucket: 'store-b683a.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzwyfcWSuLsXx-dnOzXgDoLh0h0I8tbRo',
    appId: '1:898169829916:ios:ca9394db78be1ac362fdd9',
    messagingSenderId: '898169829916',
    projectId: 'store-b683a',
    storageBucket: 'store-b683a.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNfmMtf-Bpcq1C5dTACL3dkgMdGSQXffk',
    appId: '1:898169829916:web:07f29e60cba7390862fdd9',
    messagingSenderId: '898169829916',
    projectId: 'store-b683a',
    authDomain: 'store-b683a.firebaseapp.com',
    storageBucket: 'store-b683a.appspot.com',
  );
}
